Weather/Controllers/ForecastController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Weather.Models;

namespace Weather.Controllers
{/// <summary>
/// A class to managed contolling the Forecast model, and forecast view.
/// </summary>
    public class ForecastController : Controller
    {

        //display the long term forecast of one of the cities, if clicked.
        public ActionResult Index(int? id)
        {
            WeatherModel model;
            ViewBag.IsMetric = GlobalVariables.IsMetric;

            switch (id)
            {
                case 0:
                    model = new WeatherModel("Vancouver");
                    return View(model);     

                case 1:
                    model = new WeatherModel("Burnaby");
                    return View(model);
                    
                case 2:
                    model = new WeatherModel("Whistler");
                    return View(model);
   
                default:
                    return View();
            }
        }


        //display the forecast of a city, if searched. 
        //incorrect searches appear to return the nearest 
        //matching city code. 
        [HttpPost]
        public ActionResult Searching(string city)
        {
            ViewBag.IsMetric = GlobalVariables.IsMetric;

            if (city != null && city != "")
            {
                WeatherModel model = new WeatherModel(city);
                return View(model);
            }
            else
            {
                WeatherModel model = new WeatherModel("Vancouver");
                return View(model);
            }
        }

    }
}

Weather/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using Weather.Models;

namespace Weather.Controllers
{
    public class HomeController : Controller
    {
        public string weatherDesription;

        public async Task<ActionResult> Index()
        {
            //the timestamp to be displayed on UI screen
            ViewBag.CurrentTime = DateTime.Now;
            ViewBag.IsMetric = GlobalVariables.IsMetric;
          
            //as per instructions, display vancouver and two other B.C. cities
            CitiesModel cities = new CitiesModel();

            WeatherModel model1 = new WeatherModel("Vancouver");
            WeatherModel model2 = new WeatherModel("Burnaby");
            WeatherModel model3 = new WeatherModel("Whistler");

            cities.Add(model1);
            cities.Add(model2);
            cities.Add(model3);

            return View(cities);
        }

        public async Task<ActionResult> ToggleTempUnits()
        {
            //toggle the bool for celsius/far and redisplay cities
            GlobalVariables.IsMetric = !GlobalVariables.IsMetric;

            //the timestamp to be displayed on UI screen
            ViewBag.CurrentTime = DateTime.Now;
            ViewBag.IsMetric = GlobalVariables.IsMetric;

            //as per instructions, display vancouver and two other B.C. cities
            CitiesModel cities = new CitiesModel();

            WeatherModel model1 = new WeatherModel("Vancouver");
            WeatherModel model2 = new WeatherModel("Burnaby");
            WeatherModel model3 = new WeatherModel("Whistler");

            cities.Add(model1);
            cities.Add(model2);
            cities.Add(model3);

            return RedirectToAction("Index", "Home");
        }

    }
}

Weather/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Weather/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Weather/Views/Home/Index.cshtml
@model Weather.Models.CitiesModel

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Weather</h1>
    <div class="allCities">
        <div class="cityWeather">
            <img src="@Model[0].IconUrl" />
            <p class="lead"><a href="@Url.Action("Index","Forecast", new { id = 0 })">@Model[0].City</a></p>
            <p class="dailyDescription">@Model[0].Description</p>
            <p class="dailyTemp">
                @Model[0].Temperature
                @if (ViewBag.IsMetric)
                {
                    @:°C</p>
                }
                else
                {
                    @:°F</p>
                }
        </div>

        <div class="cityWeather" id="city2">
            <img src="@Model[1].IconUrl" />
            <p class="lead"><a href="@Url.Action("Index","Forecast", new { id = 1 })">@Model[1].City</a></p>
            <p class="dailyDescription">@Model[1].Description</p>
            <p class="dailyTemp">
                @Model[1].Temperature
                @if (ViewBag.IsMetric)
                {
                    @:°C</p>
                }
                else
                {
                    @:°F</p>
                }
        </div>

        <div class="cityWeather" id="city3">
            <img src="@Model[2].IconUrl" />
            <p class="lead"><a href="@Url.Action("Index","Forecast", new { id = 2 })">@Model[2].City</a></p>
            <p class="dailyDescription">@Model[2].Description</p>
            <p class="dailyTemp">
                @Model[2].Temperature
                @if (ViewBag.IsMetric)
                {
                    @:°C</p>
                }
                else
                {
                    @:°F</p>
                }
        </div>
    </div>
    <div class="searchForm">
        @using (Html.BeginForm("Searching", "Forecast"))
        {
            @Html.TextBox("city", null, new { @class = "searchBox" })
            <input class="searchButton" type="submit" name="SaveButton" value="Search" />
        }
    </div>
</div>

<p>@ViewBag.CurrentTime</p>
<input class="toggleUnitButton" type="button" value="Toggle C/F" onclick="location.href='@Url.Action("ToggleTempUnits", "Home")'" />